<?php

return [
    'batting_columns' => [
        0  => 'number',
        1  => 'name',
        2  => 'bats',
        3  => 'avg',
        4  => 'games',
        5  => 'pa',
        6  => 'ab',
        7  => 'runs',
        8  => 'hits',
        9  => 'infield_hits',
        10 => 'infield_hit_pct',
        11 => 'doubles',
        12 => 'triples',
        13 => 'hr',
        14 => 'hr_detail',
        15 => 'total_bases',
        16 => 'rbi',
        17 => 'strikeouts',
        18 => 'walks',
        19 => 'ibb',
        20 => 'hbp',
        21 => 'sac_bunts',
        22 => 'sac_flies',
        23 => 'stolen_bases',
        24 => 'caught_stealing',
        25 => 'sb_pct',
        26 => 'errors',
        27 => 'passed_balls',
        28 => 'gidp',
        29 => 'risp',
        30 => 'obp',
        31 => 'slg',
        32 => 'ops',
    ],

    'pitching_columns' => [
        0  => 'number',
        1  => 'name',
        2  => 'throws',
        3  => 'last_game',
        4  => 'era',
        5  => 'games',
        6  => 'starts',
        7  => 'relief',
        8  => 'consec_games',
        9  => 'consec_days',
        10 => 'wins',
        11 => 'losses',
        12 => 'holds',
        13 => 'saves',
        14 => 'hold_points',
        15 => 'save_points',
        16 => 'relief_wins',
        17 => 'relief_losses',
        18 => 'complete_games',
        19 => 'shutouts',
        20 => 'no_bb_games',
        21 => 'win_pct',
        22 => 'innings',
        23 => 'batters_faced',
        24 => 'pitches',
        25 => 'pitches_per_inning',
        26 => 'hits_allowed',
        27 => 'hr_allowed',
        28 => 'strikeouts',
        29 => 'walks',
        30 => 'ibb',
        31 => 'hbp',
        32 => 'wp',
        33 => 'balks',
        34 => 'runs',
        35 => 'er',
    ],
];


